---
# Install Docker and Docker Compose on Ubuntu

# Ensure system is updated
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# Install required dependencies
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: yes

# Add Docker GPG key
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

# Add Docker APT repository
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
  become: yes

# Install Docker
- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
  become: yes

# Start and enable Docker service
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

# Install Docker Compose
- name: Download Docker Compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 'u+x'
  become: yes

# Verify Docker Compose installation
- name: Verify Docker Compose version
  command: /usr/local/bin/docker-compose --version
  register: result
  failed_when: result.rc != 0
  changed_when: false
  become: yes

# Add user to Docker group
- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

# Refresh group membership (manual logout required)
- name: Refresh group membership (manual logout required)
  shell: "newgrp docker"
  become: yes
  ignore_errors: yes
