---
# Ensure system is updated
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# Install required dependencies
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
  become: yes

# Add Docker GPG key
- name: Add Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

# Add Docker APT repository
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
  become: yes

# Install Docker
- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes

# Start and enable Docker service
- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

# Install Docker Compose plugin (recommended method)
- name: Install Docker Compose Plugin
  apt:
    name: docker-compose-plugin
    state: latest
  become: yes

# Verify Docker Compose installation
- name: Verify Docker Compose version
  command: docker compose version
  register: result
  failed_when: result.rc != 0
  changed_when: false
  become: yes

# Add user to Docker group
- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

# Notify user to log out and log back in
- name: Notify user about Docker group change
  debug:
    msg: "Please log out and log back in for Docker group changes to take effect."
